Add `getparams` and `setparams!!` following `AbstractMCMC` v5.5
TuringLang/AdvancedMH.jl pull request #103
Opened 2024-10-21 06:34 UTC by sunxd3

ref: https://github.com/TuringLang/Turing.jl/issues/2367

2024-10-22 10:44 UTC, sunxd3 commented
the test is failing because an numerical test (https://github.com/TuringLang/AdvancedMH.jl/actions/runs/11434545096/job/31870916921?pr=103#step:5:353) 
should we relax the `atol`, and is this new?

2024-10-22 21:34 UTC, penelopeysm reviewed
The PRNG generates different numbers on different Julia versions even if the seed is set the same, so I guess 1234 was just an unlucky choice 😅

2024-10-22 21:34 UTC, penelopeysm commented on test/runtests.jl
> +    end
```suggestion
    @testset "getparams/setparams!! (AbstractMCMC interface)" begin
        t1, _ = AbstractMCMC.step(Random.default_rng(), model, StaticMH([Normal(0, 1), Normal(0, 1)]))
        t2, _ = AbstractMCMC.step(Random.default_rng(), model, MALA(x -> MvNormal(x, I)); initial_params=ones(2))
        for t in [t1, t2]
            @test AbstractMCMC.getparams(t) == t.params
            @test AbstractMCMC.setparams!!(t, AbstractMCMC.getparams(t)) == t
            t_replaced = AbstractMCMC.setparams!!(t, (μ=1.0, σ=2.0))
            @test t_replaced.params == (μ=1.0, σ=2.0)
        end
    end
```

I guess we should test `MALA` too. Does this work?

2024-10-23 11:09 UTC, penelopeysm approved these changes

2024-10-23 11:10 UTC, penelopeysm commented
Oh, one more thing, should it be 0.9.0 rather than 0.8.4? Since we're introducing new functions.

2024-10-24 22:55 UTC, torfjelde commented
> Oh, one more thing, should it be 0.9.0 rather than 0.8.4? Since we're introducing new functions.

It's a bit weird, but basically, at least to my understanding, when we haven't reached version 1 yet, we use minor version as what is considered "breaking" and patch version for everything that isn't. Once we have non-zero major version, then we bump minor version when we introduce new (even non-breaking) functionality. Sooo in this case, I say we stick with bumping patch version.

2024-10-24 23:03 UTC, torfjelde requested changes
This PR suffers from the same issues I've raised in AdvancedHMC.jl: gradient information will be out of sync.

This means that if you do something like
```julia
AbstractMCMC.step(model, sampler, setparams!!(state, new_params))
```
you'll use the incorrect gradient in the MH step, resulting in the incorrect chain. I've outlined what I think we should do here: https://github.com/TuringLang/AdvancedHMC.jl/pull/378#pullrequestreview-2393847647

2024-10-31 11:17 UTC, torfjelde requested changes
Looks good! Just need to remove the BangBang.jl references.

2024-10-31 11:17 UTC, torfjelde commented on Project.toml
> +BangBang = "0.3.19, 0.4"
I'm assuming this is left-over from when you were using BangBang.jl? We're no longer using it, right?

2024-10-31 11:17 UTC, torfjelde commented on src/AdvancedMH.jl
> +using BangBang
```suggestion
```

2024-10-31 12:59 UTC, sunxd3 commented
good call! now removed, thanks a lot for reviewing this all these times

2024-10-31 13:24 UTC, merged